### ISSUE TITLE
systemctl edit iotedge.service not linked to iotedge.service file on CentOS

### ISSUE THREAD

**Issue by microsoftman** [Azure/azure-iotedge#3]
**Issue:** When running IoT Edge on the CentOS preview, using the steps in the [troubleshooting documentation](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot) to call "sudo systemctl edit iotedge.service", this opens an empty file.  The iotedge.service file appears to be located at /usr/lib/systemd/iotedge.service when running CentOS. Editing this file is needed for turning on debug mode.

**Expected Output:** The iotedge.service file should be opened with the existing configurations to edit, such as turning on the debug mode under the [Service] block.

**Repo Steps:** 

1. Create a CentOS 7.5 VM from the Azure Marketplace
2. SSH into the VM and copy the latest libiothsm and iotedge RPMs to the home directory
3. Run the following commands to install Docker CE and IoT Edge:
4. sudo yum upgrade -y
5. sudo yum install -y yum-utils device-mapper-persistent-data lvm2
6. sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
7. sudo yum install -y docker-ce
8. sudo systemctl enable docker
9. sudo systemctl start docker
10. sudo yum localinstall -y libiothsm-std-1.0.1-0.1.<version_goes_here>.x86_64.rpm
11. sudo yum localinstall -y iotedge-1.0.1-0.1.<version_goes_here>.x86_64.rpm
12. Call: sudo systemctl edit iotedge.service    to notice the empty file is loaded

**Environment:** CentOS-Based 7.5 (Rogue Wave Software) VM image in the Azure Marketplace

**Comment by darobs** [comment]
Hello @microsoftman,

Usually, the `systemctl edit` command creates a new file, usually named something like `iotedge.service.d/override.conf`, so you would normally expect the initial edit command to open an empty file.  This `override.conf` would be merged with the installed `iotedge.service` by systemd. 

This may vary depending on the version of systemd, but this is the behavior I've observed on our supported systems.  The instructions should work as advertised.  

I'm closing this issue, but please open a new issue on [the iotedge development repo](https://github.com/Azure/iotedge) if you are still having issues.
