### ISSUE TITLE
Can this repository be closed as a duplicate?

### ISSUE THREAD

**Issue by theangellmethod** [Azure/azure-iotedge#8]
It looks like all of the code and issues for Azure IoT Edge are here - https://github.com/Azure/iotedge .  It is odd to google for 'Azure IoT Edge' and land in this repository.

**Comment by ondrejspilka** [comment]
@theangellmethod  Can you see RPM packages in https://github.com/Azure/iotedge ?

**Comment by theangellmethod** [comment]
I am not sure what RPM means - what am I looking for?

**Comment by chipalost** [comment]
Hi @theangellmethod, we understand that multiple repos can easily create confusion; however we need both to accurately differentiate between the open source project and Microsoft product. This is necessary for legal purposes.
   * Azure IoT Edge, open source project - https://github.com/azure/iotedge/
   * Azure IoT Edge, Microsoft product - https://github.com/Azure/azure-iotedge/
We also understand why one would post bugs on the issues page of the product repo; however we try and do our coding in the open source project. That is why we request that issues are reported on the issues page of that repo.
